# build.yml is used for defining workflows in your repository,
# specifying how code should be built and tested.
name: Java CI with Maven

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test
        |
         run: mvn -B package --file pom.xml
